### ISSUE TITLE
Command Request - gdl-gaben

### ISSUE THREAD

**Issue by TheRockettek** [GDLDiscord/BotAndServer#33]
The world must be prepared for this command. If not it can cause an unstable anomaly occur in the space time fracture which would cause an explosion. It will show the public one of the most gracious images of Gabe Newell preforming one of his most well known acts of reducing steam games to barely anything. These days more people are aware of this man as GabeN than jesus christ himself.

# __All hail GabeN, our lord and saviour

![image](https://user-images.githubusercontent.com/17106916/26951938-1dfa607a-4c9b-11e7-8070-514e4a0757dd.png)

**Comment by VulcanGDL** [comment]
I will do this soon and add to the current jesus cog and rename the cog

**Comment by VulcanGDL** [comment]
changed jesus cog folder into images by:
class images:

updated data file too images from jesus

**Comment by VulcanGDL** [comment]
done
